### ISSUE TITLE
Set Min/Max selectable dates

### ISSUE THREAD

**Issue by Xpjay** [JoshHalvorson/calendar-date-range-picker#24] opened 2021-09-08 10:46 UTC
**Is your feature request related to a problem? Please describe.**
Possibility to define a min and max selectable dates, that's mean dates a not selectable before minDate and after maxDate.
unselectable date are "Grey"

**Additional context**
Something like, be free to use a more relevant name `eventCalendar.setSelectableDates(minCalendar, maxCalendar)
`

**Comment by JoshHalvorson** [comment] 2021-09-08 17:08
Almost a duplicate of #6 , gonna close this and update the other issue with some of the stuff you put here. Thanks!

**Closed as completed by JoshHalvorson** 2021-09-08 17:08 UTC
